create table if not exists public.contatos (
  id bigint generated by default as identity primary key,
  nome text not null,
  empresa text not null,
  mensagem text not null,
  created_at timestamptz not null default now()
);

alter table public.contatos enable row level security;

create policy "Permitir envio público de contatos"
on public.contatos
for insert
to anon
with check (true);
